---
- name: Include version-specific variables for RedHat.
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= 6

- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'


- name: Define cups_packages.
  set_fact:
    cups_packages: "{{ __cups_packages | list }}"
    when: cups_packages is not defined

# Install Tasks

- include: setup-RedHat.yml
  static: no
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  static: no
  when: ansible_os_family == 'Debian'
