---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_distribution != 'Ubuntu' or ansible_distribution != 'Fedora'

- name: Define cups_packages.
  set_fact:
    cups_packages: "{{ __cups_packages | default([]) }}"
    when: cups_packages is not defined

# Install Tasks

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup=Debian.yml
  when: ansible_os_family == 'Debian'
